### PR TITLE
Fix blockquote layout

### PR DESCRIPTION
**Pull request by depoulo**
especially for narrow screens

test with https://developer.epages.com/blog/coding/how-to-keep-up-your-code-quality/

### CODE REVIEW

**Comment by BirgitBader** [comment]
@unabris After talking to Anne, here's what we suggest: 

* Could you please take over the styling from the quotes already used on the "About" page
* Please add a source link, see the following screenshot
Screenshot 2020-01-07 at 15 48 42

**Comment by unabris** [comment]
@BirgitBader 

Screenshot 2020-01-09 at 10 59 35

**Comment by unabris** [comment]
@BirgitBader is it ok to just use `_Source: [Link name](https://somepage.com)_` or we need something more specific?

**Comment by BirgitBader** [comment]
@unabris I think that's fine :)

**Comment by unabris** [comment]
@depoulo 
I created a PR for you that includes a jekyll plugin for adding quotes: https://github.com/depoulo/epages-devportal-1/pull/1. After you merge the PR you can use `{% quote text="your quote text goes here" %}` for displaying it on your markdown

**Comment by cgebken** [comment]
Replaced by https://github.com/ePages-de/epages-devportal/pull/592

**Pull request closed without merging**
