### PR TITLE
New blog post: Onboarding more than saying “Hello”

### PR DESCRIPTION
**Pull request by AliceStatler**

### CODE REVIEW

**Review by cgebken — COMMENTED** [review]
Let me explain some of my suggestions :)

- In general, I really like the topic and the post!
- The author of the quote in the first sentence should be stated.
- You are using "ecommerce software" and "online shop". Thus I tried to avoid the third term "platform".
- "So much helps much" felt weird to me but it might actually be okay. Still, I'd suggest "The more the better".
- Some of the explanations in the "Usability heuristics" were 1:1 the text from the graphic, which didn't really have additional value and, if used, should be made a quote. I've rewritten it a bit instead.
- We should try to avoid he/him and use they/them instead.
- The last section was pretty similar to the first one and didn't have much value for the reader. Instead it was a bit too much "marketing-ish"? I've added a suggestion :)

Question:
- Where did she get /assets/img/pages/blog/images/design-guidelines-iso.png from? If she didn't create it on her own, we need to add a source.
- Should we come up with a sentence between "Good design needs no explanation" and "Dialogue principles" explaining what this section is about/ what it includes? :)

**Comment by AliceStatler** [comment]
>     * The author of the quote in the first sentence should be stated.
I suppose this is already done with adding "Cambridge Dictionary" to the sentence (?).

>     * We should try to avoid he/him and use they/them instead.
Yes, I know. I've already changed it accordingly in some sentences, but I completely missed it in some paragraphs. Thanks for correcting them!


> Question:

>     * Where did she get /assets/img/pages/blog/images/design-guidelines-iso.png from? If she didn't create it on her own, we need to add a source.
I created it so we don't have the source issue. 

>     * Should we come up with a sentence between "Good design needs no explanation" and "Dialogue principles" explaining what this section is about/ what it includes? :)
I thought about it but I don't think it's 100% necessary here. It would be nice though so we avoid having two titles in a row here. Maybe something like "Even though good design needs no explanation it can still follow some guidelines. Therefore, we will look at some of them and see what we can apply to the onboarding process."

**Comment by cgebken** [comment]
> I suppose this is already done with adding "Cambridge Dictionary" to the sentence (?).

Yes it is :)

> I created it so we don't have the source issue.

That's awesome! :-O :D 👍 

> I thought about it but I don't think it's 100% necessary here. It would be nice though so we avoid having two titles in a row here. Maybe something like "Even though good design needs no explanation it can still follow some guidelines. Therefore, we will look at some of them and see what we can apply to the onboarding process."

I really like the first sentence but I'd slightly adjust the second one as we do not really cover the "what we can apply to the onboarding process" part (IMO): "Even though good design needs no explanation, it can still follow some guidelines. Therefore, we will have a look at some of them in the following section and outline the most important takeaways for an onboarding process."


Furthermore, I've seen that you've added the author description and I stumbled upon "focus" (focuses?) and "customers" (merchants?). When thinking about this, the following suggestion came to my mind: "is part of our UX team. Her focus is on creating a great usability of our products to transform our merchants from ecommerce novices to successful online shop operators with zero downtime." But it's just an idea I wanted to share with you :)

**Comment by AliceStatler** [comment]
> Furthermore, I've seen that you've added the author description and I stumbled upon "focus" (focuses?) and "customers" (merchants?). When thinking about this, the following suggestion came to my mind: "is part of our UX team. Her focus is on creating a great usability of our products to transform our merchants from ecommerce novices to successful online shop operators with zero downtime." But it's just an idea I wanted to share with you :)

"Just an idea.." and presents an (almost) perfect sentence. :D However, Peter was so kind to give it a little native speaker check and we came up with this:
"is a crucial member of our UX team. Her focus is on improving the usability of our products to transform our merchants from ecommerce novices to successful online shop professionals with zero downtime."

**Pull request merged**
